all: main clean

main: main.o read_and_write.o functions.o
	gcc main.o read_and_write.o functions.o -o myapp -lpng

main.o: main.c read_and_write.o functions.o read_and_write.h functions.h
	gcc -c main.c

input.o: read_and_write.c read_and_write.h
	gcc -c read_and_write.c

functions.o: functions.c functions.h
	gcc -c functions.c

clean:
	rm -f *.o
